name: " Reporte de Bug"
description: "Reporta un error para ayudarnos a mejorar."
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Descripci贸n del Bug"
      description: "Una descripci贸n clara y concisa de lo que sucede."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "Pasos para Reproducir"
      description: "Explica c贸mo llegas al error paso a paso."
      placeholder: |
        1. Ir a '...'
        2. Hacer click en '....'
        3. Ver error '....'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Comportamiento Esperado"
      description: "Qu茅 es lo que deber铆a haber sucedido."
  - type: textarea
    id: environment
    attributes:
      label: "Entorno"
      description: "Versi贸n de Node, navegador, SO, etc."
